from typing import Protocol, runtime_checkable

from memoryweave.memory.episodic_store import Episode


@runtime_checkable
class EpisodicStoreProtocol(Protocol):
    def write(self, episode: Episode) -> None: ...
    def retrieve(self, query: str, top_k: int) -> list[Episode]: ...
    def apply_decay(self, current_turn: int, decay_lambda: float) -> None: ...
    def update_entity_links(self, episode_id: str, entity_ids: list[str]) -> None: ...
    def increment_turn(self) -> int: ...
    @property
    def turn_count(self) -> int: ...


@runtime_checkable
class KGAgentProtocol(Protocol):
    def retrieve_context(self, entity_ids: list[str]) -> str: ...
    def extract_and_update(self, content: str, episode_id: str) -> list[str]: ...
